name: jsdict
description: A new Flutter project.
publish_to: 'none'

version: 1.2.2+9

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  app_links: ^6.3.2
  audioplayers: ^6.0.0
  collection: ^1.17.0
  dynamic_color: ^1.6.5
  expandable_text: ^2.3.0
  expansion_tile_card: ^3.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_svg: ^2.0.9
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.4
  get_it: ^8.0.0
  html: ^0.15.3
  http: ^1.0.0
  infinite_scroll_pagination: ^4.0.0
  lint: ^2.3.0
  package_info_plus: ^8.0.2
  provider: ^6.0.5
  receive_sharing_intent: ^1.6.8
  ruby_text:
    git: # fork adds extra alignment options
      url: https://github.com/petlyh/RubyText
      ref: 492b148c9fddfbbc03658063efc76f51d1e851c1 
  share_plus: ^10.0.2
  shared_preferences: ^2.1.2
  url_launcher: ^6.1.10
  xml: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  test: ^1.24.9

flutter_launcher_icons:
  android: true
  image_path: "assets/icon.png"
  adaptive_icon_foreground: "assets/icon-foreground.png"
  adaptive_icon_background: "#1a3332"

flutter:
  uses-material-design: true

  assets:
    - assets/kanjivg/LICENSE.kanjivg.txt
    - assets/kanjivg/kanjivg_data
